# Generated by Django 5.2.7 on 2025-10-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager_app', '0002_remove_profile_role_profile_email_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
