# Generated by Django 5.2.7 on 2025-11-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager_app', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_favorite',
        ),
    ]
